---
apiVersion: v1
kind: Secret
metadata:
  name: hpgrahsl-dev-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/backstage-2w7cf/hpgrahsl-poi-gateway-app-gitops
